# permissions for end users to view apiexampleas.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: apiexamplea-viewer-role
rules:
- apiGroups:
  - groupa.k8s.zhuang.com
  resources:
  - apiexampleas
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - groupa.k8s.zhuang.com
  resources:
  - apiexampleas/status
  verbs:
  - get
